const traineeData = [
  {
    "seq": "1",
    "dept": "R&D팀",
    "position": "책임",
    "job": "R&D",
    "empId": "1007338",
    "name": "오양석",
    "processLvl": "(선택)",
    "maintLvl": "중급",
    "qualityLvl": "중급",
    "email": "yangseok.oh@sampyo.co.kr",
    "phone": "010-6301-7011"
  },
  {
    "seq": "2",
    "dept": "R&D팀",
    "position": "매니저",
    "job": "R&D",
    "empId": "1008568",
    "name": "임희아",
    "processLvl": "중급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "1008568@sampyo.co.kr",
    "phone": "010-9515-5739"
  },
  {
    "seq": "3",
    "dept": "공정개선팀",
    "position": "책임",
    "job": "생산관리",
    "empId": "1008255",
    "name": "이순혁",
    "processLvl": "(선택)",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "soonhyeok.lee@sampyo.co.kr",
    "phone": "010-2073-1465"
  },
  {
    "seq": "4",
    "dept": "공정개선팀",
    "position": "책임",
    "job": "생산관리",
    "empId": "1008253",
    "name": "정신환",
    "processLvl": "(선택)",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "shinhwan.jung@sampyo.co.kr",
    "phone": "010-4370-9135"
  },
  {
    "seq": "5",
    "dept": "광산생산팀",
    "position": "수석",
    "job": "생산기획",
    "empId": "1007171",
    "name": "고영민",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "youngmin.goh@sampyo.co.kr",
    "phone": "010-6668-3246"
  },
  {
    "seq": "6",
    "dept": "광산생산팀",
    "position": "책임",
    "job": "생산관리",
    "empId": "1008320",
    "name": "이원섭",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "wonsup.lee@sampyo.co.kr",
    "phone": "010-8973-3301"
  },
  {
    "seq": "7",
    "dept": "기계팀",
    "position": "매니저",
    "job": "기계설비",
    "empId": "1008621",
    "name": "김국송",
    "processLvl": "제외",
    "maintLvl": "제외",
    "qualityLvl": "제외",
    "email": "1008621@sampyo.co.kr",
    "phone": "#N/A"
  },
  {
    "seq": "8",
    "dept": "기계팀",
    "position": "책임",
    "job": "기계설비",
    "empId": "1008326",
    "name": "김창용",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "changyong.kim@sampyo.co.kr",
    "phone": "010-2899-2941"
  },
  {
    "seq": "9",
    "dept": "기계팀",
    "position": "책임",
    "job": "기계설비",
    "empId": "1008256",
    "name": "신성웅",
    "processLvl": "초급",
    "maintLvl": "(선택)",
    "qualityLvl": "초급",
    "email": "sungwoong.shin@sampyo.co.kr",
    "phone": "010-6364-7563"
  },
  {
    "seq": "10",
    "dept": "기계팀",
    "position": "책임",
    "job": "기계설비",
    "empId": "1007556",
    "name": "홍성훈",
    "processLvl": "초급",
    "maintLvl": "중급",
    "qualityLvl": "초급",
    "email": "seonghun.hong@sampyo.co.kr",
    "phone": "010-3279-3794"
  },
  {
    "seq": "11",
    "dept": "기술팀",
    "position": "책임",
    "job": "설비/공사",
    "empId": "1007337",
    "name": "김영욱",
    "processLvl": "초급",
    "maintLvl": "중급",
    "qualityLvl": "초급",
    "email": "youngwook.kim@sampyo.co.kr",
    "phone": "010-8383-4838"
  },
  {
    "seq": "12",
    "dept": "기술팀",
    "position": "책임",
    "job": "설비/공사",
    "empId": "1008154",
    "name": "이기수",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "gisoo.lee@sampyo.co.kr",
    "phone": "010-5099-0443"
  },
  {
    "seq": "13",
    "dept": "보전관리팀",
    "position": "수석",
    "job": "생산관리",
    "empId": "1008200",
    "name": "배장석",
    "processLvl": "초급",
    "maintLvl": "중급",
    "qualityLvl": "초급",
    "email": "jangseok.bae@sampyo.co.kr",
    "phone": "010-6373-9117"
  },
  {
    "seq": "14",
    "dept": "보전관리팀",
    "position": "책임",
    "job": "기계설비",
    "empId": "1008258",
    "name": "이동원",
    "processLvl": "초급",
    "maintLvl": "중급",
    "qualityLvl": "초급",
    "email": "dongwon.lee@sampyo.co.kr",
    "phone": "010-8879-5202"
  },
  {
    "seq": "15",
    "dept": "보전관리팀",
    "position": "책임",
    "job": "기계설비",
    "empId": "1007553",
    "name": "이진희",
    "processLvl": "초급",
    "maintLvl": "(선택)",
    "qualityLvl": "초급",
    "email": "jinhee2.lee@sampyo.co.kr",
    "phone": "010-9478-4078"
  },
  {
    "seq": "16",
    "dept": "생산1팀",
    "position": "매니저",
    "job": "생산관리",
    "empId": "1008619",
    "name": "박희범",
    "processLvl": "중급",
    "maintLvl": "초급",
    "qualityLvl": "중급",
    "email": "huibeom.park@sampyo.co.kr",
    "phone": "010-2998-0633"
  },
  {
    "seq": "17",
    "dept": "생산1팀",
    "position": "수석",
    "job": "생산관리",
    "empId": "1007320",
    "name": "이유형",
    "processLvl": "(선택)",
    "maintLvl": "(선택)",
    "qualityLvl": "중급",
    "email": "yuhyung.lee@sampyo.co.kr",
    "phone": "010-4534-0701"
  },
  {
    "seq": "18",
    "dept": "생산1팀",
    "position": "매니저",
    "job": "생산관리",
    "empId": "1008618",
    "name": "최민규",
    "processLvl": "중급",
    "maintLvl": "중급",
    "qualityLvl": "중급",
    "email": "mingyu.choi@sampyo.co.kr",
    "phone": "010-2614-3452"
  },
  {
    "seq": "19",
    "dept": "생산2팀",
    "position": "수석",
    "job": "생산관리",
    "empId": "1007327",
    "name": "김동현",
    "processLvl": "(선택)",
    "maintLvl": "(선택)",
    "qualityLvl": "중급",
    "email": "donghyun.kim@sampyo.co.kr",
    "phone": "010-2864-9881"
  },
  {
    "seq": "20",
    "dept": "생산2팀",
    "position": "책임",
    "job": "생산관리",
    "empId": "1008321",
    "name": "박상진",
    "processLvl": "중급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "sj.park@sampyo.co.kr",
    "phone": "010-9968-4225"
  },
  {
    "seq": "21",
    "dept": "생산2팀",
    "position": "매니저",
    "job": "생산관리",
    "empId": "1008620",
    "name": "정희경",
    "processLvl": "중급",
    "maintLvl": "중급",
    "qualityLvl": "초급",
    "email": "hg.jung@sampyo.co.kr",
    "phone": "010-6512-5687"
  },
  {
    "seq": "22",
    "dept": "생산기획팀",
    "position": "책임",
    "job": "생산기획",
    "empId": "1007588",
    "name": "남광현",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "kwanghyun.nam@sampyo.co.kr",
    "phone": "010-7396-1126"
  },
  {
    "seq": "23",
    "dept": "생산기획팀",
    "position": "책임",
    "job": "생산기획",
    "empId": "1007580",
    "name": "이혜진",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "hyejin.lee@sampyo.co.kr",
    "phone": "010-2686-6405"
  },
  {
    "seq": "24",
    "dept": "순환자원파트",
    "position": "책임",
    "job": "생산관리",
    "empId": "1007331",
    "name": "윤인한",
    "processLvl": "중급",
    "maintLvl": "초급",
    "qualityLvl": "중급",
    "email": "inhan.yoon@sampyo.co.kr",
    "phone": "010-9439-4477"
  },
  {
    "seq": "25",
    "dept": "안전보건팀",
    "position": "책임",
    "job": "보건",
    "empId": "1007420",
    "name": "김보애",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "boae.kim@sampyo.co.kr",
    "phone": "010-4977-1000"
  },
  {
    "seq": "26",
    "dept": "안전보건팀",
    "position": "수석",
    "job": "환경안전",
    "empId": "1008521",
    "name": "신승호",
    "processLvl": "초급",
    "maintLvl": "중급",
    "qualityLvl": "초급",
    "email": "seungho.shin@sampyo.co.kr",
    "phone": "010-7454-3363"
  },
  {
    "seq": "27",
    "dept": "안전보건팀",
    "position": "책임",
    "job": "환경안전",
    "empId": "1007336",
    "name": "조경찬",
    "processLvl": "제외",
    "maintLvl": "제외",
    "qualityLvl": "제외",
    "email": "1007336@sampyo.co.kr",
    "phone": "#N/A"
  },
  {
    "seq": "28",
    "dept": "안전보건팀",
    "position": "매니저",
    "job": "환경안전",
    "empId": "1008683",
    "name": "홍성호",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "seongho.hong@sampyo.co.kr",
    "phone": "010-7540-2259"
  },
  {
    "seq": "29",
    "dept": "운영지원팀",
    "position": "책임",
    "job": "생산관리",
    "empId": "1008707",
    "name": "유다건",
    "processLvl": "초급",
    "maintLvl": "중급",
    "qualityLvl": "초급",
    "email": "dagun.yoo@sampyo.co.kr",
    "phone": "010-3304-0784"
  },
  {
    "seq": "30",
    "dept": "전기팀",
    "position": "책임",
    "job": "설비/공사",
    "empId": "1008261",
    "name": "김세중",
    "processLvl": "초급",
    "maintLvl": "(선택)",
    "qualityLvl": "초급",
    "email": "sejung.kim@sampyo.co.kr",
    "phone": "010-5100-8030"
  },
  {
    "seq": "31",
    "dept": "전기팀",
    "position": "수석",
    "job": "설비/공사",
    "empId": "1007074",
    "name": "김종태",
    "processLvl": "초급",
    "maintLvl": "(선택)",
    "qualityLvl": "초급",
    "email": "jongtae.kim@sampyo.co.kr",
    "phone": "010-8609-2157"
  },
  {
    "seq": "32",
    "dept": "전기팀",
    "position": "책임",
    "job": "설비/공사",
    "empId": "1008324",
    "name": "박건",
    "processLvl": "초급",
    "maintLvl": "(선택)",
    "qualityLvl": "초급",
    "email": "geon.park@sampyo.co.kr",
    "phone": "010-7276-6404"
  },
  {
    "seq": "33",
    "dept": "전기팀",
    "position": "수석",
    "job": "설비/공사",
    "empId": "1005970",
    "name": "송창근",
    "processLvl": "제외",
    "maintLvl": "제외",
    "qualityLvl": "제외",
    "email": "changgeun.song@sampyo.co.kr",
    "phone": "010-4642-1003"
  },
  {
    "seq": "34",
    "dept": "제품팀",
    "position": "수석",
    "job": "생산관리",
    "empId": "1007169",
    "name": "고시원",
    "processLvl": "(선택)",
    "maintLvl": "(선택)",
    "qualityLvl": "중급",
    "email": "siwon.ko@sampyo.co.kr",
    "phone": "010-5356-9688"
  },
  {
    "seq": "35",
    "dept": "제품팀",
    "position": "책임",
    "job": "생산관리",
    "empId": "1007967",
    "name": "정윤수",
    "processLvl": "중급",
    "maintLvl": "중급",
    "qualityLvl": "초급",
    "email": "yoonsoo.jeong@sampyo.co.kr",
    "phone": "010-7907-4025"
  },
  {
    "seq": "36",
    "dept": "품질팀",
    "position": "책임",
    "job": "품질관리",
    "empId": "1007335",
    "name": "김상진",
    "processLvl": "중급",
    "maintLvl": "중급",
    "qualityLvl": "중급",
    "email": "sangjin.kim@sampyo.co.kr",
    "phone": "010-3352-1162"
  },
  {
    "seq": "37",
    "dept": "품질팀",
    "position": "수석",
    "job": "품질관리",
    "empId": "1005936",
    "name": "안상원",
    "processLvl": "초급",
    "maintLvl": "중급",
    "qualityLvl": "(선택)",
    "email": "sangwon.ahn@sampyo.co.kr",
    "phone": "010-9071-7935"
  },
  {
    "seq": "38",
    "dept": "품질팀",
    "position": "책임",
    "job": "품질관리",
    "empId": "1008254",
    "name": "오민석",
    "processLvl": "중급",
    "maintLvl": "초급",
    "qualityLvl": "중급",
    "email": "minseok.oh@sampyo.co.kr",
    "phone": "010-2965-1891"
  },
  {
    "seq": "39",
    "dept": "품질팀",
    "position": "수석",
    "job": "품질관리",
    "empId": "1007329",
    "name": "임두섭",
    "processLvl": "중급",
    "maintLvl": "초급",
    "qualityLvl": "(선택)",
    "email": "doosub.lim@sampyo.co.kr",
    "phone": "010-4158-9218"
  },
  {
    "seq": "40",
    "dept": "순환자원파트",
    "position": "책임",
    "job": "생산관리",
    "empId": "1007334",
    "name": "정의식",
    "processLvl": "중급",
    "maintLvl": "초급",
    "qualityLvl": "(선택)",
    "email": "wuisik.jung@sampyo.co.kr",
    "phone": "010-2770-6602"
  },
  {
    "seq": "41",
    "dept": "환경팀",
    "position": "수석",
    "job": "환경안전",
    "empId": "1008296",
    "name": "김지현",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "jihyun.kim@sampyo.co.kr",
    "phone": "010-9580-0362"
  },
  {
    "seq": "42",
    "dept": "환경팀",
    "position": "책임",
    "job": "환경안전",
    "empId": "1008325",
    "name": "이인욱",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "inuk.lee@sampyo.co.kr",
    "phone": "010-9174-6849"
  },
  {
    "seq": "43",
    "dept": "안전보건팀",
    "position": "책임",
    "job": "환경안전",
    "empId": "1008682",
    "name": "김준배",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "junbae.kim@sampyo.co.kr",
    "phone": "010-5084-1367"
  },
  {
    "seq": "44",
    "dept": "운영지원팀",
    "position": "매니저",
    "job": "생산관리",
    "empId": "1008735",
    "name": "김형준",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "hyungjun.kim@sampyo.co.kr",
    "phone": "010-8996-6626"
  },
  {
    "seq": "45",
    "dept": "공정개선팀",
    "position": "매니저",
    "job": "생산관리",
    "empId": "K24081",
    "name": "이준호",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "john987abc@sampyo.co.kr",
    "phone": "010-9982-5884"
  },
  {
    "seq": "46",
    "dept": "광산생산팀",
    "position": "수석",
    "job": "생산관리",
    "empId": "1007172",
    "name": "권민수",
    "processLvl": "초급",
    "maintLvl": "초급",
    "qualityLvl": "초급",
    "email": "minsoo.kwon@sampyo.co.kr",
    "phone": "010-5455-0134"
  },
  {
    "seq": "47",
    "dept": "인사팀",
    "position": "교육담당자",
    "job": "교육운영",
    "empId": "ADMIN_JU",
    "name": "주용현",
    "processLvl": "전체",
    "maintLvl": "전체",
    "qualityLvl": "전체",
    "email": "younghyun.ju@sampyo.co.kr",
    "phone": "010-8527-8084"
  }
];
